### ISSUE TITLE
选了4张图片，大小在5兆左右 OOM

### ISSUE THREAD

**Issue by bbqichang** [Curzibn/Luban#45]

**Comment by hundange** [comment]
遇到同样情况，有时上传一张照片，OOM
08-15 16:08:10.121: E/AndroidRuntime(16941): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 1046540 byte allocation with 353744 free bytes and 345KB until OOM
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban.saveImage(Luban.java:428)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban.compress(Luban.java:390)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban.thirdCompress(Luban.java:240)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban.access$2(Luban.java:184)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban$5.call(Luban.java:123)
08-15 16:08:10.121: E/AndroidRuntime(16941): 	at com.axon.luban.Luban$5.call(Luban.java:1)

**Comment by Curzibn** [comment]
@hundange 能否把你那张出现OOM的图片发到我邮箱？我这边暂时找不到会OOM的图片

**Comment by hundange** [comment]
这个跟图片大小和机型有关，不是每次都OOM，我这边是直接用红米note 3 机型直接拍摄的，照片大小4,7M，在saveImage 方法中第一次压缩将压缩率options 值根据bitmap大小去设置可以解决OOM问题，我这边改成50是没问题的

**Comment by 2tu** [comment]
难道得判断一下当前剩余内存，动态设置inSampleSize
